use_frameworks!

target 'HUPageController_Example' do
  pod 'HUPageController', :path => '../'

  target 'HUPageController_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
