platform :ios, ‘8.0’
use_frameworks!

target 'HUPageController_Example' do
  pod 'HUPageController', :path => '../'

  target 'HUPageController_Tests' do
    inherit! :search_paths

#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
            config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ''
        end
    end
end
